# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProfileSaverExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProfileSaverExample
  pod 'SnapKit'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/Buttons'
  pod 'RealmSwift'

  target 'ProfileSaverExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
